# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=100)),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
                ('Avatar', models.ImageField(null=True, upload_to='images')),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
