# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Birthdate', models.DateField(null=True)),
                ('Sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='F', max_length=1)),
                ('Avatar', models.ImageField(null=True, upload_to='Avatars')),
            ],
        ),
    ]
