# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_name', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
            ],
        ),
    ]
