# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proiect', '0003_auto_20170118_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=100)),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
                ('Avatar', models.ImageField(null=True, upload_to='images')),
                ('Rating', models.IntegerField()),
                ('Destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proiect.Destination')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
