# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proiect', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Avatar',
        ),
        migrations.AddField(
            model_name='review',
            name='Photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
