# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proiect', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Review',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Proiect.Review'),
            preserve_default=False,
        ),
    ]
