# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proiect', '0005_auto_20170121_1223'),
        ('Proiect', '0005_comment_review'),
    ]

    operations = [
    ]
